{% set name = "legacy-api-wrap" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 175b7b8af157eedb5b3dbc941e2fbff7cc9da2880382cbb8ea3a01c73404b81e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - get_version >=2.0.4
    - flit >=1.3
  run:
    - python >=3.6
    - get_version >=2.0.4

test:
  imports:
    - legacy_api_wrap

about:
  home: https://github.com/flying-sheep/legacy-api-wrap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "Wrap legacy APIs in python projects."

extra:
  recipe-maintainers:
    - raivivek
