{% set name = "legacy-api-wrap" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 92dfa274cedb26d6e6f70fac85c856fbdcc05058066656d76a665fb4bf11b785

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
    - hatch-docstring-description
  run:
    - python >=3.8

test:
  imports:
    - legacy_api_wrap

about:
  home: https://github.com/flying-sheep/legacy-api-wrap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "Wrap legacy APIs in python projects."

extra:
  recipe-maintainers:
    - raivivek
    - flying-sheep
